envs:
    num_envs: 2
    use_cuda: False
    num_updates: 10
    num_steps_per_update: 64
    randomize_domain: False

train:
    input_file_path: "C:/Users/jsp2288.park/Desktop/RLStudy/SchedulingProblem/data/taillard/open_shop_scheduling/tai4_4.txt"
    num_instance_limit: 1

agent:
    name: A2C
    actor_lr: 0.001
    critic_lr: 0.005
    lam: 0.95  # hyperparameter for GAE
    gamma: 0.999
    entropy_coef: 0.01  # coefficient for the entropy bonus (to encourage exploration)
    
model_utils:
    save_weights: True
    load_weights: False
    actor_weights_path: weights/actor.pth
    critic_weights_path: weights/critic.pth

hyperparameters:
    epochs: 10
    batch_size: 64
    learning_rate: 0.001
